### ISSUE TITLE
iCal timezone should reflect blog timezone

### ISSUE THREAD

**Issue by ThemeBoy** [ThemeBoy/SportsPress#122]
As per https://wordpress.org/support/topic/calendar-time-zone?replies=2#post-6624059 the iCal feeds are generating events using GMT but should be using the same timezone as the originating blog.

**Comment by RocketHockeyLeague** [comment]
Has this been repaired? We would love to add Google Calendar to our ThemeBoy Premier site!

**Comment by RepairmanSki** [comment]
Just came across this issue today on our team page. Thankfully I noticed the (2 year old!) bug before I published to the supporters. Be nice to see this on the roadmap/changelog soon.

**Comment by brianmiyaji** [comment]
@RepairmanSki Ah, this should have been closed as it was fixed in d50d242b14c7783c979123bb59b6ab291f7f48fb

**Comment by RepairmanSki** [comment]
@brianmiyaji You're (mostly) correct in that the implementation of the webcal standard is functioning as expected.  There is a problem, however when using the Google link (ex: http://www.google.com/calendar/render?cid={URL}%3Ffeed%3Dsp-ical) in that Google's implementation is broken.  There are 8+ years of angry support posts on the Google Calendar forum to corroborate this claim.  

Effectively, when adding the calendar from hyperlink, the events default to GMT-0/UTC and nothing at all can be done to affect the timezone status of a particular calendar within that environment.

The 'resolution' is to manually subscribe by webcal URL as referenced in this Google Support post: https://support.google.com/calendar/answer/37100?co=GENIE.Platform%3DDesktop&hl=en

In terms of what to do on the SportsPress side, I would strongly consider removing the Google link generation and creating a kb article explaining the issue.  Any team manager publishing the generated link is going to have a bad time dealing with end-user frustration regarding incorrect time values.
