### ISSUE TITLE
Scores missing from Event page/screen

### ISSUE THREAD

**Issue by mharriswales** [ThemeBoy/SportsPress#123]
Hi,

For some unknown reason all of the scores have disappeared from the Event page (see attached) although the scores are still recorded against each event.

As far as I can tell this happened shortly after I changed a calculation in the configuration section.

Please help!

Regards,
M Harris
![missing scores](https://cloud.githubusercontent.com/assets/11502079/6665735/dbae04ea-cbd4-11e4-8fed-38a89df483da.png)

**Comment by ThemeBoy** [comment]
@mharriswales The score displayed next to the team names will be the primary result. To change this, go to SportsPress > Configure, scroll down to the Event Results section and click the button in the "Primary" column next to the result that you'd like to display. For example, in football it would be "Goals".

**Comment by mharriswales** [comment]
Not only do you produce a fantastic product but have equally fantastic
support....!

Thank you.
Mark

On 16 March 2015 at 12:23, ThemeBoy <notifications@github.com> wrote:

> @mharriswales <https://github.com/mharriswales> The score displayed next
> to the team names will be the primary result. To change this, go to
> SportsPress > Configure, scroll down to the Event Results section and click
> the button in the "Primary" column next to the result that you'd like to
> display. For example, in football it would be "Goals".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThemeBoy/SportsPress/issues/123#issuecomment-81617021>
> .
>



-- 
Mark Harris MAAT

Honarary Treasurer
Dinas Powis RFC

**Comment by ThemeBoy** [comment]
Glad I could help :)
