### ISSUE TITLE
Frontend Styles input validation

### ISSUE THREAD

**Issue by jkarppinen** [ThemeBoy/SportsPress#151]
From Settings -> General -> Frontend Styles, it is possible to input and save any text to custom color textboxes. This is not expected behaviour, as there should at least be a warning about invalid input.

It should validate:
* input with max. 6 characters, or 7 characters if there's a number sign (f.ex. #000000)
* all characters between 0-9 and a-f, not case-sensitive

Could you please confirm this?

**Comment by ThemeBoy** [comment]
@jkarppinen You're right, validation would be useful here. We'll be adding it shortly.
