### ISSUE TITLE
Error after PHP7 upgrade

### ISSUE THREAD

**Issue by carletto0282** [ThemeBoy/SportsPress#158]
Hi guys,

I'm facing this error after the upgrade to PHP7

```
Fatal error: Uncaught Error: Call to undefined function sp_array_value() in /mysite/public_html/wp-content/plugins/sportspress/includes/sp-template-hooks.php:297 
```

It already came up twice.
If I remove the plugin the system works again.
If I switch back to PHP 5.6.17 it works again.

Please fix this I really need to have the system working with PHP7
Best regards
Carlo

**Comment by savvasha** [comment]
Already fixed!
