### ISSUE TITLE
Error with register_rest_fields

### ISSUE THREAD

**Issue by redhell** [ThemeBoy/SportsPress#171]
Hi,
when i try to open the jetpack site i'll get following error:

Fatal error: Call to undefined function register_rest_field() in /httpdocs/wp-content/plugins/sportspress/includes/api/class-sp-rest-api.php on line 63

Latest PHP 5.6 FPM with Wordpress 4.6.

**Comment by brianmiyaji** [comment]
@redhell Thanks! Does this solve the error?
https://github.com/ThemeBoy/SportsPress/commit/5f6182ea011162dfffdebce708634bee51443f01

**Comment by redhell** [comment]
Works thanks. 
https://core.trac.wordpress.org/ticket/34730 I've found this while i looked for a solution.
