### ISSUE TITLE
NBA players number

### ISSUE THREAD

**Issue by dmattiola** [ThemeBoy/SportsPress#185]
There is an issue with the players number.
My web site contains nba players and number could be "0" or "00". I save this but in my players list the number doesn't appear !
![capture](https://cloud.githubusercontent.com/assets/6717174/20004325/015eb3c6-a28c-11e6-9589-fd7639afb67f.PNG)

**Comment by brianmiyaji** [comment]
@dmattiola Thanks for your feedback! This has been fixed in 2f11effaa540d70a57e5015e41d68662e91b4686
