### ISSUE TITLE
Limit the results of players lists

### ISSUE THREAD

**Issue by midomario** [ThemeBoy/SportsPress#187]
hi, 
It would be great to have the possibility of not showing the entire list of players. But only the 10 first of a list. It coup speed up the loading of the page

For example : The best scorers of the league : now i get 600 results !! And even with the pagination, the loading of the page is a bit long

**Comment by brianmiyaji** [comment]
@midomario Thanks for your feedback! I've added this option in version 2.2 :) 3ca3485b286885c938535d4221ad3af165f1b43d
