### ISSUE TITLE
Timed Statistics bug

### ISSUE THREAD

**Issue by DeValladolid** [ThemeBoy/SportsPress#189]
`Fatal error: Uncaught Error: Call to undefined function ereg_replace() in /customers/4/5/3/---.com/httpd.www/wp-content/plugins/sportspress/includes/class-sp-player-list.php:645 Stack trace: #0 /customers/4/5/3/---.com/httpd.www/wp-content/plugins/sportspress/templates/player-gallery.php(57): SP_Player_List->data() #1 /customers/4/5/3/---.com/httpd.www/wp-content/plugins/sportspress/includes/sp-core-functions.php(80): include('/customers/4/5/...') #2 /customers/4/5/3/---.com/httpd.www/wp-content/plugins/sportspress/includes/widgets/class-sp-widget-player-gallery.php(38): sp_get_template('player-gallery....', Array) #3 /customers/4/5/3/---.com/httpd.www/wp-includes/class-wp-widget.php(395): SP_Widget_Player_Gallery->widget(Array, Array) #4 /customers/4/5/3/---.com/httpd.www/wp-includes/widgets.php(738): WP_Widget->display_callback(Array, Array) #5 /customers/4/5/3/---.com/httpd.www/wp-content/themes/rookie/footer.php(22): dynamic_sid in /customers/4/5/3/---.com/httpd.www/wp-content/plugins/sportspress/includes/class-sp-player-list.php on line 645`

**Comment by brianmiyaji** [comment]
@DeValladolid Thanks for noticing this! Since ereg_replace was removed in PHP 7, we're replacing this with preg_replace 32d446710b5f42f2d411b5b8cf8e67e4dab38c5c
