### ISSUE TITLE
The icons do not appear

### ISSUE THREAD

**Issue by DeValladolid** [ThemeBoy/SportsPress#190]
![descarga](https://cloud.githubusercontent.com/assets/22749943/21954371/d22c9460-da4e-11e6-91ae-f3dd15142000.png)
![descarga 1](https://cloud.githubusercontent.com/assets/22749943/21954390/89b6904a-da4f-11e6-9aa0-d82440e94794.png)

**Comment by brianmiyaji** [comment]
@DeValladolid these icons are used in the Box Score section of events, which can be enabled via SportsPress > Events > Box Score > Mode > Icons.

In player profiles and other areas, the values will always be displayed as a number.

Of course, you can submit this idea to the [Ideaboard](http://tboy.co/ideas) for others to vote it up :)

**Comment by DeValladolid** [comment]
ok , thx
