### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by DeValladolid** [ThemeBoy/SportsPress#191]
`Warning: A non-numeric value encountered in /customers/4/5/3/balonmanozaratan.com/httpd.www/wp-content/plugins/sportspress/includes/class-sp-league-table.php on line 310`
URL: [balonmanozaratan.com](https://www.balonmanozaratan.com)

**Comment by DeValladolid** [comment]
Solved, php 7.1 does not work.

**Comment by DeValladolid** [comment]
but 7.0 work perfect

**Comment by brianmiyaji** [comment]
@DeValladolid Ah, thanks for letting me know! Looks like PHP 7.1 is throwing errors when adding non-numeric values. Converting to floatval to prevent this issue in da12f410fb3e5a3aa2ee84f8aafc3e949ce7ab13
