### ISSUE TITLE
Career Stats

### ISSUE THREAD

**Issue by yoye** [ThemeBoy/SportsPress#192]
It looks like a really weird behavior on career stats. I have created stats for a player for the last 4 seasons. I really appreciate to have total of all year rows so I activate "show total" on player settings. But on the player page there is 2 tables for stats. One of them is empty.

Does I misunderstand domething ?

### Here is the player page
![sans-titre-1](https://cloud.githubusercontent.com/assets/570307/21958335/6b58ad1a-daac-11e6-99ac-afb20c4b3f8b.jpg)

### Here is the admin page
![sans-titre-2](https://cloud.githubusercontent.com/assets/570307/21958336/6b7ca10c-daac-11e6-888a-dc5cdd9f300b.jpg)

**Comment by brianmiyaji** [comment]
@yoye Ah, the empty table can be removed by unselecting the **Total - Display total** option under Player Settings. However, this will also remove the "Total" row at the bottom of the first table. I'll add an option to differentiate between these :)

**Comment by brianmiyaji** [comment]
Added separate setting for displaying career totals efa1895da7e9c91773fe5802f639544c23197503
