### ISSUE TITLE
box Score headings are not showing after updating 2.2.7

### ISSUE THREAD

**Issue by michas66** [ThemeBoy/SportsPress#193]
After updating today from 2.26 to 2.27, the headings of box score  are not being shown. here is the page of my website 

http://p-z.gr/event/c-drifters-vs-heat-bc/

**Comment by DeValladolid** [comment]
Waiting for the update :)

**Comment by brianmiyaji** [comment]
@michas66 @DeValladolid fixed in f4e3ef41783eaf4a1e22fc7a7deb395b13ca3bb4
