### ISSUE TITLE
I can not edit a league table

### ISSUE THREAD

**Issue by Vinicius12fc** [ThemeBoy/SportsPress#202]
Dear

After the last update of the SportsPress plugin, I can no longer edit the league table. The teams and the columns are not showing up anymore, so I can not change the number of wins, draws, losses, points ... those variables for each team, which should be on the league table.

In the visible part of the site (front end) the table follows how it was before the last update of the plugin. I need to make changes and now I can not. Are there any plans to fix this? Or is there any way I can go back to the previous version of the plugin?

![sem titulo](https://cloud.githubusercontent.com/assets/26613270/24227842/04e254fa-0f4f-11e7-90b9-5313383b605e.jpg)

![sem titulo1](https://cloud.githubusercontent.com/assets/26613270/24227908/7b5d24ac-0f4f-11e7-8a9a-b2971093530c.jpg)

**Comment by brianmiyaji** [comment]
@Vinicius12fc It looks like the meta box is hidden. Could you click on "Screen Options" (Opções de Tela) in the top right corner, and make sure that the "League Table" (Tabela de Liga) option is selected?

**Comment by Vinicius12fc** [comment]
@brianmiyaji Thanks for the answer. I tried clicking on this option, but it does not open on this screen (in other Wordpress tabs it opens normally).

![sem titulo2](https://cloud.githubusercontent.com/assets/26613270/24228376/825d96e4-0f52-11e7-84cf-89d074ccd039.jpg)

**Comment by brianmiyaji** [comment]
@Vinicius12fc Okay, there must be a JS error somewhere. Could you open the console (cmd+opt+J on Mac Chrome) and tell me if you see any errors there?

**Comment by Vinicius12fc** [comment]
Can this image answer you?

![sem titulo3](https://cloud.githubusercontent.com/assets/26613270/24229091/9ccc5f84-0f56-11e7-9c39-748721bf6089.jpg)

**Comment by brianmiyaji** [comment]
@Vinicius12fc Thanks for the screenshot. I think I found the issue, we had a function that is only available in PHP version 5.5 and later, which would cause an error for earlier versions. Here is the line to change:
https://github.com/ThemeBoy/SportsPress/commit/a1b1bf342665fed503f25cbb9dd0fd8c03cedf89

**Comment by Vinicius12fc** [comment]
Sorry, but I could not understand what exactly I should do to solve the problem. Where do I change this line?

**Comment by brianmiyaji** [comment]
@Vinicius12fc We've just released version 2.3.1 which includes this patch, so you can download it here: https://github.com/ThemeBoy/SportsPress/archive/master.zip

Let me know if this issue is fixed once you update :)

**Comment by Vinicius12fc** [comment]
@brianmiyaji I ended up finding the place where I made the line change in the plugin editor. After the change, the function I needed reappeared. Thank you so much, really.

**Comment by brianmiyaji** [comment]
@Vinicius12fc Glad to hear that! Thanks for your valuable feedback :)
