### ISSUE TITLE
Error when editing a league table

### ISSUE THREAD

**Issue by fhervazquez** [ThemeBoy/SportsPress#203]
i get this after the last update:

Fatal error: Call to undefined function boolval() in /home/***/public_html/wp-content/plugins/sportspress/includes/sp-core-functions.php on line 562

**Comment by brianmiyaji** [comment]
@fhervazquez Ah, this is an error that occurs with PHP < 5.5. It's been fixed in https://github.com/ThemeBoy/SportsPress/commit/a1b1bf342665fed503f25cbb9dd0fd8c03cedf89 and available in SportsPress 2.3.1

**Comment by fhervazquez** [comment]
Thanks, I found the last commit and the fixed after I posted this. Also the update came out this morning. Great plugin guys.
