### ISSUE TITLE
[Event] Player 'Substitute' status formatting on backend

### ISSUE THREAD

**Issue by danfisher85** [ThemeBoy/SportsPress#220]
If you go to **Events > Event** and change a player status from **Starting Lineup** to **Substitute** you will see that additional fields added at the right side http://take.ms/8plYp 
Probably it's ok if you have just a few stats, but if you add additional ones you will see the following http://take.ms/HD7lm
I think it would be better to place those elements at the bottom of the status field.

**Comment by brianmiyaji** [comment]
@danfisher85 Good point! This was affected by this commit in 2.5:
ead879c1ac67af4e28aaba0eb239f924edde7ed8

I'll add some line breaks after the substitute dropdowns :)
