### ISSUE TITLE
Bug with Image type icon for Player Performance (sp_performance)

### ISSUE THREAD

**Issue by danfisher85** [ThemeBoy/SportsPress#221]
Steps to reproduce:
1. Go to **SportsPress > Configure > Player Performance**
2. Find **Goals** and click on Edit
3. Find **Icon** box, click **Image** and then **Select Icon**
4. Find or upload your image icon and click **Select Icon**
5. No image selected and icon switched back to previous one.
6. If you click on **Image** select again your image will be attached, but I'm pretty sure it's not how it supposed to be.

Please check a quick video guide http://take.ms/XgA4U

Browser: Safari 11.0.1
OS: macOS 10.12.6
WordPress: 4.9
Theme: Rookie
SportsPress version: 2.5.1

**Comment by brianmiyaji** [comment]
@danfisher85 Thanks! I'll look into these issues today.
