### ISSUE TITLE
Height and Weight

### ISSUE THREAD

**Issue by cesarfreitasdesigner** [ThemeBoy/SportsPress#225]
There's a way to change the words "Height" and "Weight" to my language, in text tab? Currently these words don't appear not even in .mo files.
![image](https://user-images.githubusercontent.com/34010739/33244375-0d47f102-d2dd-11e7-8d3d-57e85dc34eb8.png)

**Comment by brianmiyaji** [comment]
@cesarfreitasdesigner The labels for "Height" and "Weight" are generally added as Player Metrics, which can be customized via the SportsPress > Configure > Player Metrics section.
