### ISSUE TITLE
CSV Import fixtures

### ISSUE THREAD

**Issue by DanteGabriel** [ThemeBoy/SportsPress#228]
There is an Error in date format validation (if exist). If you import a .csv file just like

> 07.01.2018,10:00,,TEAM I,TEAM II
> 07.01.2018,11:00,,TEAM III,TEAM IV
> 07.01.2018,12:00,,TEAM VI,TEAM I

you'll see, that the importer confirmed "import successfully", but no match was added. (No change in the number of all matches) If you do the same and replay "," with "/" everything is fine.

Of couse during the import process a message was shown, that the date format have to be a value with "/", but it seems to be wrong, if the importer confirmed that the import is "done", and doesn't abort, if the date format is wrong.

**Comment by savvasha** [comment]
Not an issue really. There is an option to select the date format before importing.
