### ISSUE TITLE
Get player list based on team id

### ISSUE THREAD

**Issue by Cronnay** [ThemeBoy/SportsPress#229]
Hello there.

I am using the REST-api that came along the plugin. Is there a possibility to retrieve a player list based on the team id? You can make a get-request with an id, but that is a player list id, which is not the same as team id.

For example:
`wp-json/sportspress/v2/lists/teamid`

**Comment by brianmiyaji** [comment]
ee6b11c3a5dfdb8abf91f8a434306928757bcfc1
