### ISSUE TITLE
Problem with Event MarkUp´s

### ISSUE THREAD

**Issue by srdrabx** [ThemeBoy/SportsPress#255]
There is an error in the MarkUps of the events.
The MarkUps don't include either name or location, which makes it not show up on Google as a "main" mistake.
![imagen](https://user-images.githubusercontent.com/22749943/37121459-76457858-225d-11e8-8bf7-92bdb030db27.png)

**Comment by Andy8407** [comment]
@DeValladolid Take a look on event-blocks.php on line 162 

Change it to following like this

`<div class="sp-event-venue" itemprop="location" itemscope itemtype="http://schema.org/Place"><span itemprop="name"><?php echo $venue->name; ?></span><meta itemprop="address" content="España"/></div>`
