### ISSUE TITLE
Import Events (scheduled)

### ISSUE THREAD

**Issue by stormbets** [ThemeBoy/SportsPress#257]
Used WP All Import plugins

When import events  in custom fields  "sp_team" placed value "234|456"
where 234 and 456 post id for Team1 and Team2.

When event saved logo and name for first Team1 are placed, but info about second Team2 not visible.

How to import events with full information?

**Comment by savvasha** [comment]
Did you try the Import Fixtures option which is included with SportsPress?
More info here: https://www.themeboy.com/blog/import-and-edit-existing-events/
