### ISSUE TITLE
Post Author select is broken

### ISSUE THREAD

**Issue by rochesterj** [ThemeBoy/SportsPress#273]
Reported by @ramzesimus here: https://wordpress.org/support/topic/post-author-select-is-broken/

Plugin: SportsPress: 2.6.4 (& Pro)
Theme: Rookie 1.5.2 (It looks like any theme will have this issue)

How to reproduce:
    Go to Posts > Post
    Make sure Author option enabled (Screen Options > Author http://take.ms/P2RKoT)
    Scroll down and at the bottom of the post you will see a broken select (see screenshot http://take.ms/yhTTR)
    Everything is ok if SportsPress plugin is deactivated (see screenshot http://take.ms/D1AIV).

****
Also, it looks like this is a script issue. When the page loads at first the select is there, then some code kicks in and breaks it. But the select is there, it's just hidden.

Thanks!

**Comment by savvasha** [comment]
There is a conflict that we have to sort it out. In the meantime there is a temporary fix for this:
https://github.com/ThemeBoy/SportsPress/commit/b27e9260d27392f31dc72fab5cec9534fc82eefb
