### ISSUE TITLE
Live Countdown widget timezone bug

### ISSUE THREAD

**Issue by danfisher85** [ThemeBoy/SportsPress#289]
I found the issue in Countdown widget if live countdown option (SportsPress > General > Scripts > Live Countdowns) enabled. 

Details:
My Local Time - UTC+2 (14:00)
My Site Time - UTC+4 (16:00)

I set up Timezone UTC+4 in SportsPress ( http://take.ms/AIK3s ) and the same timezone is in General > Settings ( http://take.ms/v3DkX ). So the site time should be 16:00

After that I scheduled an Event for <strong>Aug 20, 2018 @ 17:00</strong>, added Countdown widget and got the wrong time ( http://take.ms/GWjJxd ) The event starts in an hour (site time 16:00, scheduled for 17:00) but it shows the time based on my local computer settings.

If live countdown is disabled everything works as expected ( http://take.ms/oNMUO )

Thanks in advance!
Dan

**Comment by savvasha** [comment]
Was fixed in 2.6.9 version.

**Comment by farrukhchik** [comment]
Hello @savvasha, 
Is that about the PRO version of the plugin? Because I can see only the 2.6.14 version of the plugin: https://wordpress.org/plugins/sportspress/ 
thanks

**Comment by savvasha** [comment]
2.6.14 is the latest version of both core and Pro versions of SportsPress.
