### ISSUE TITLE
Empty Array response from API (tables, lists)

### ISSUE THREAD

**Issue by burzumumbra** [ThemeBoy/SportsPress#316]
I have tested the API in 2.6.13, but ther's a problem, I can't acces Tables, Lists and similars. The call to wp-json/sportspress/v2 Shows that for example in list I ther's 4 elements, and then if I go to
wp-json/sportspress/v2/lists or wp-json/sportspress/v2/tables I got as response an empty array.
![api fail 2](https://user-images.githubusercontent.com/4171009/50033815-bed0ee00-ffbf-11e8-9e37-d2ea818d0f2e.PNG)
![api fail](https://user-images.githubusercontent.com/4171009/50033817-bed0ee00-ffbf-11e8-8238-73bf4a8c582e.PNG)

**Comment by brianmiyaji** [comment]
@burzumumbra Thanks for testing this. You're right, the endpoints for secondary post types (tables, lists, etc) were still following the old logic. I've fix this and we've released version 2.6.14 which should resolve the issue.
