### ISSUE TITLE
Live Countdown widget Bug

### ISSUE THREAD

**Issue by realleoman** [ThemeBoy/SportsPress#320]
Hello guys:

I'm having an issue with the Live Countdown widget.  I have the latest version installed (2.6.14) on my WP installation and when watching the Live Countdown in my site, I see the texts for the days, hrs, mins, segs in English and the time is 6 hours ahead of my local timezine (GMT-6) Mexico City.

<img width="1440" alt="screen shot 2019-02-20 at 3 59 49 pm" src="https://user-images.githubusercontent.com/699501/53127889-155f2900-3529-11e9-81e4-4001157d6af1.png">

But when editing the Live Countdown with WP Bakery Page Builder, I can see the texts for days, hrs, mins, segs in Spanish and the countdown timezone is OK. After I click on Update, the texts and timezone returns as the previous image.

<img width="1438" alt="screen shot 2019-02-20 at 3 57 26 pm" src="https://user-images.githubusercontent.com/699501/53127890-155f2900-3529-11e9-9ad7-6e03101b3410.png">

SportsPress is already set to UTC-6 (I have also tried selecting Mexico City too with no luck

<img width="1074" alt="screen shot 2019-02-20 at 4 08 11 pm" src="https://user-images.githubusercontent.com/699501/53128137-bfd74c00-3529-11e9-90b8-a06107fb7bbe.png">

And my WordPress site is also set to UTC-6 (also changed to Mexico City timezone, but no luck)

<img width="1070" alt="screen shot 2019-02-20 at 4 09 11 pm" src="https://user-images.githubusercontent.com/699501/53128188-e1383800-3529-11e9-913d-4a1ed0d9ca5c.png">

Any ideas about how to fix it?

**Comment by savvasha** [comment]
If you add the Countdown widget in a sidebar without using WP Bakery plugin, the time is still wrong?

**Comment by realleoman** [comment]
Hi @savvasha . Not able to see the countdown widget in the list to place it the sidebar... Just the Events but it only shows me the events date but not the countdown.. Any other ideas?

![widgets cruz azul futbol club wordpress](https://user-images.githubusercontent.com/699501/53210911-16658880-3605-11e9-924c-7c1e537876a1.jpg)

**Comment by savvasha** [comment]
Ok. Perhaps your theme or any other plugin replacing SportsPress Countdown widget with their own. Please disable all your plugins except SportsPress and switch to a default theme like `Rookie` or `TwentySeventeen`.
![image](https://user-images.githubusercontent.com/6088209/53221029-2797af00-3670-11e9-95e8-5232e5104bd6.png)


Thanks

**Comment by realleoman** [comment]
They are using Wp Bakery Page Builder and they have the Next Match object (I guess that one includes a counter).

Are those items related somehow with SportPress?

<img width="395" alt="screen shot 2019-03-06 at 4 36 37 pm" src="https://user-images.githubusercontent.com/699501/53918917-0b135380-402e-11e9-9b39-9e7544f846fc.png">
