### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by meadsports** [ThemeBoy/SportsPress#337]
Issue with importing events. Stops after 20 events. I have increased the max exec time to 360 and increased memory. Still same issue.

**Comment by rtucker-scs** [comment]
I'm unfortunately seeing the same behavior.

**Comment by rtucker-scs** [comment]
guh, ended up being my fault. I, possibly like you upgraded to PHP7 before the EOL. 

I had to set max_input_vars in  /etc/php/7.1/apache2/php.ini
