### ISSUE TITLE
How to translate 'View all clubs'?

### ISSUE THREAD

**Issue by therampagerado** [ThemeBoy/SportsPress#358]
I can't find this string anywhere.

Sportspress - latest free version
Rockie - latest free version

**Comment by danfisher85** [comment]
@therampagerado 'View all clubs' is a string of **SportsPress for Football (Soccer)** extension. So, you can find it there (see screenshot https://take.ms/P0jU6)

**Comment by therampagerado** [comment]
Thank you!
