### ISSUE TITLE
Hide Birthday 

### ISSUE THREAD

**Issue by talli22** [ThemeBoy/SportsPress#363]
When you select hide birthday, it permanently removes it. Becuase when you untick the box the age does not come back

**Comment by talli22** [comment]
/modules/sportspress-hide-birthday.php

**Comment by savvasha** [comment]
Thanks for the feedback. Can you check with the new commit? https://github.com/ThemeBoy/SportsPress/commit/84656b86dba755ec923ea46a55daba2132dc0d56

Thanks,
Savvas
