### ISSUE TITLE
Big empty space beetwen video and next line

### ISSUE THREAD

**Issue by betisweb** [ThemeBoy/SportsPress#376]
Hi all
this is my first post

You can see a big distance from video resumen upto next line “detalles”

How  can I solve this problem, thks

https://www.betisweb.com/web/event/j25-real-betis-rcd-mallorca/

**Comment by betisweb** [comment]
A friend info that problem is coming from here https://imgur.com/a/KMbPeZm

**Comment by betisweb** [comment]
????

**Comment by savvasha** [comment]
Hi @betisweb ,
Please make your question at WP Forums (https://wordpress.org/support/plugin/sportspress/) not in github.

Thanks,
Savvas
