### ISSUE TITLE
Match list desplegable, current match day 

### ISSUE THREAD

**Issue by jionji** [ThemeBoy/SportsPress#394]
Hello. To show the list of matches I want to know if you can put a dropdown for match days like the League Manager plugin. Also that a code can be used to automatically show the current day on the page, as I currently have with that plugin. Matchday = current
https://www.fspozodeguadalajara.com/zzzleaguemanager.png
https://www.fspozodeguadalajara.com/zzzleaguemanager2.png

Thanks!

**Comment by savvasha** [comment]
Hi @jionji ,

Please use the[ SportsPress support forums](https://wordpress.org/support/plugin/sportspress/) for this kind of questions.

Thanks,
Savvas
