### ISSUE TITLE
Load shortcodes via ajax

### ISSUE THREAD

**Issue by AtarAktos** [ThemeBoy/SportsPress#397]
Hi,
I need to load a shorcode (event_list) in ajax mode onload page, to avoid caching problems.
May someone help me?

I can't understand the use of the file "class-sp-ajax.php" in "includes" directory, maybe it helps?

Dittmar

**Comment by savvasha** [comment]
Hi @AtarAktos ,
You should give a look at the following articles that explain how you can achieve what you want:
https://codex.wordpress.org/AJAX_in_Plugins
https://www.sitepoint.com/how-to-use-ajax-in-wordpress-a-real-world-example/
https://medium.com/techcompose/how-to-use-ajax-precisely-in-wordpress-custom-themes-dc61616720a8
https://premium.wpmudev.org/blog/using-ajax-with-wordpress/

Long story short: You dont have to use the `class-sp-ajax.php` file. You create a function that calls `event_list` shortcode` and then you are calling this function through a javascript-ajax code.

For support its better to use the [WP forum](https://wordpress.org/support/plugin/sportspress/) :)

Thanks,
Savvas
