### ISSUE TITLE
Google and Outlook calendars show incorrect event times

### ISSUE THREAD

**Issue by danis039** [ThemeBoy/SportsPress#410]
Hi guys, 

I know this has been addressed in #122 - which has been closed - however, the problem still seems to persist.

I'm currently using Warsaw timezone on my site (UTC+1, currently in daylight saving time), and both my Google and Outlook calendars always display the event times two hours ahead in comparison to the ones I set. Apple Calendar, on the other hand, displays the correct times.

The issue happens both when adding automatically via the specific generated Google Calendar link or adding the calendar manually on Google Calendar/Outlook.

You can check the issue by subscribing to the following calendar with the different apps (notice how Apple Calendar displays the time two hours before, which is the correct time):
[webcal://www.dragoonsfc.com/calendar/dragoons-calendar?feed=sp-ical](webcal://www.dragoonsfc.com/calendar/dragoons-calendar?feed=sp-ical)

Thanks a lot for your great work on this kick-ass plugin! :)

**Comment by savvasha** [comment]
Hmmm, is this similar to what described by @RepairmanSki at https://github.com/ThemeBoy/SportsPress/issues/122#issuecomment-285431192 ?

**Comment by danis039** [comment]
> Hmmm, is this similar to what described by @RepairmanSki at [#122 (comment)](https://github.com/ThemeBoy/SportsPress/issues/122#issuecomment-285431192) ?

Not really, because the issue does not only affect Google Calendar, but Outlook as well. Adding the calendar manually doesn't solve it either.

**Comment by savvasha** [comment]
I am trying to see the actual calendar from your site. Is www.dragoonsfc.com/calendar/dragoons-calendar not available?

**Comment by savvasha** [comment]
![image](https://user-images.githubusercontent.com/6088209/118802668-110e4b80-b8ab-11eb-9703-eeaae3d9b59b.png)
In the ical is the same:
`BEGIN:VEVENT
SUMMARY:Dragoons vs Wieczysta II
UID:349
STATUS:CONFIRMED
DTSTAMP:19700101T000000
DTSTART:20210523T140058
DTEND:20210523T153058
LAST-MODIFIED:20210515T104413
LOCATION:KS Nadwiślan Kraków\, Koletek 20\, 31-069 Kraków
GEO:50.0513575;19.9363066
END:VEVENT`

I am not sure why Google and Outlook do not respect this...

**Comment by danis039** [comment]
Here's the weird thing, on my test environment, the calendar times are working as expected! But not in production...

I've enabled calendar pages so you can have a look if needed:

**Prod**:
https://www.dragoonsfc.com/calendar/dragoons-calendar/

**Test**:
https://dragoonsfc.com/test/calendar/dragoons-calendar/

By checking the timestamps, they seem to be the same... any ideas?

**Comment by savvasha** [comment]
Are you sure that is everything the same in both your WP environments? Did you check the date/time settings of WP and SportsPress? Are both in the same server with the same settings? If you download both ical files and search for differences, you will see that they dont have the same time for each event. So the problem is not on Google/Outlook or Apple. Something is set different in your production site.

Test site ical: https://dragoonsfc.com/test/calendar/dragoons-calendar?feed=sp-ical
Prod site ical: https://www.dragoonsfc.com/calendar/dragoons-calendar?feed=sp-ical

**Comment by danis039** [comment]
This seems to be a cache (or something similar) problem. I've created a new calendar with the same settings and a new slug, and it works as expected. However, when I change its slug back to https://www.dragoonsfc.com/calendar/dragoons-calendar/ and add it back to Google Calendar, the wrong dates are displayed once again. Changing the name/slug fixes the issue.

**Comment by savvasha** [comment]
At least you found a workaround 👍

**Comment by danis039** [comment]
> At least you found a workaround 👍

Thanks for your help :) The only issue is having to change the calendar URL, which would impact users that have already subscribed. Perhaps Google will refresh the cache for this one some time soon, I'll have to wait and see. Cheers!
