### ISSUE TITLE
Different Stats if Logged In

### ISSUE THREAD

**Issue by eselje** [ThemeBoy/SportsPress#411]
On my team stats page, a game is excluded if I'm not logged into the system. Once I log in, the same page shows all of the games.

Example:

https://imgur.com/a/WfvpZVM

**Comment by savvasha** [comment]
Hi @eselje ,

What are the settings of the event that is excluded? What if delete it and re-create it?

Thanks,
Savvas

**Comment by eselje** [comment]
What's interesting is that *eventually* the stats align. Sometimes it's a
day or two later. No amount of cache clearing, rebooting, switching
browsers makes a difference - only logging in or out. I'd love to know
what's going on behind the scenes here.

I've confirmed the settings are a Competitive game, so they should count.

**Comment by savvasha** [comment]
There should be an issue with your date/time settings between guest (not logged in) and logged in users. Doesn't seem to be a SportsPress issue...
