### ISSUE TITLE
Ultimate member registered not showing as player profile

### ISSUE THREAD

**Issue by AzmayenFayek** [ThemeBoy/SportsPress#415]
When I'm registering with ultimate member registration then that info is not showing in newly created players
can you please solve this issue
thanks in advance

**Comment by savvasha** [comment]
Hi @AzmayenFayek ,
It doesnt seem as a SportsPress issue. Did you try to use the native WP registration form?

Thanks,
Savvas

**Comment by AzmayenFayek** [comment]
I need many info like birth day, gender, phone number in registration form.
So I'm not using native wp registration form

**Comment by savvasha** [comment]
You may need to discuss it with UM development team then.
https://wordpress.org/support/topic/um-with-sportspress-plugin/
https://wordpress.org/support/topic/custom-registration-8/
https://wordpress.org/support/topic/sportspress-3/

**Comment by AzmayenFayek** [comment]
Ok

**Comment by AzmayenFayek** [comment]
They replied me as:

"Hi @AzmayenFayek <https://github.com/AzmayenFayek>

Does Sportspress store the user data in wp_users and wp_usermeta tables? UM
stores user data in those two tables. You can ask Sportspress regarding
this storage and let's see if we can find a way to integrate the two.

Regards, ”

**Comment by savvasha** [comment]
Well SportsPress Players are a Custom Post Type with the type of `sp_player`. There birthday is actually the `post_date` of each Player. All other fields are either saved as `post-meta` info or as `taxonomy terms`. So unfortunately no, there are no data stored in wp_users or wp_usermeta tables. But there support team said here https://wordpress.org/support/topic/sportspress-3/#post-12588101 that it is possible to make those two plugins communicate. Maybe with some custom code from your side that will work as a bridge between UM and SportsPress

**Comment by AzmayenFayek** [comment]
But please think for it. How can be it relevant birthday and post date?

**Comment by savvasha** [comment]
This is how SportsPress is designed :)
