### ISSUE TITLE
OpenStreetMaps not showing

### ISSUE THREAD

**Issue by Skylerrer** [ThemeBoy/SportsPress#421]
I observed that OpenStreetMaps was not longer showing up in Sportspress Version 2.7.9

I figured out that it was because of an error in SportsPress/assets/js/leaflet.js

In commit 23ba2446b17a6f0f204104978014595ac8984ccb from Nov 13, 2021 the name of the function  _e(t,i)
was changed to esc_attr_e(t,i) .
Which lead to an reference error.

For me the problem was solved by renaming the function to the original name again.

**Comment by savvasha** [comment]
Hi @Skylerrer ,

It should be fixed with https://github.com/ThemeBoy/SportsPress/commit/7ea3f36072d8b2558031c73bdf162a91c9979d6d

**Comment by Skylerrer** [comment]
Yes. Thanks!
