### ISSUE TITLE
iCal calendar problems

### ISSUE THREAD

**Issue by sgurlt** [ThemeBoy/SportsPress#434]
Hi,

I am currently facing two issues with the iCal Calendar:
1. After moving the site from my stage to production, the calendar does not show any results using the iCal URL
2. The iCal calendar showed the wrong event times (seems like timezone related)

The WordPress timezone is set to “Berlin”:
https://prnt.sc/Hx2v8vkQUBI_

The Sportspress timezone is set to “Berlin”:
https://prnt.sc/MnAmNW5kki2K

Here is my next upcoming event (23.04.2022 15:00 / 3pm)
https://www.wiesbaden-phantoms.de/event/wiesbaden-phantoms-vs-saarland-hurricanes/

This is what the event looks like in WordPress:
– https://prnt.sc/TxY4OSaNwhWS
– https://prnt.sc/Mzi65oo6wJW_

This is what the calendar looks like in WordPress (I don’t understand why all dates are shown as “27. September 2021” btw.):
https://prnt.sc/AkaGwE7S4X_L

Problem number 1 – No Events added to the Google calendar at all (Production site):
http://www.google.com/calendar/render?cid=webcal%3A%2F%2Fwww.wiesbaden-phantoms.de%2Fcalendar%2Fkalender%3Ffeed%3Dsp-ical

Problem number 2 – Events showing the wrong times:
http://www.google.com/calendar/render?cid=webcal%3A%2F%2Fredesign.wiesbaden-phantoms.de%2Fcalendar%2Fkalender%3Ffeed%3Dsp-ical

Help is very welcome 🙂

Best regards,
Sebastian

**Comment by danis039** [comment]
Same issues here.

- Calendar works as expected with Apple Calendar and Outlook, but does not work with Google Calendar at all
- All calendar entries have the same date in the backend (correct dates are shown in the frontend)

**Comment by robjr14** [comment]
Same issues for me. Same date shown for all entries in backend and google calendar doesn't show the correct time. Time zone for wordpress/sportspress is set to Toronto (Canada - EST) but yet if sportspress calendar shows a 7h30pm start time for a match, google calendar will show it as 4h30pm - Important to note that sportspress is the only calendar import that messes up the times.

**Comment by lusky3** [comment]
Just to throw some confusion in: I do not have this issue.

The link imported into my Google Calendar lists the game a 9:30PM.
![image](https://user-images.githubusercontent.com/22225233/167029483-f59a0fcd-eaa4-4585-916a-0d15ac83b36f.png)

Which matches what's on the site.
![image](https://user-images.githubusercontent.com/22225233/167029659-4199c122-1b95-438a-addd-9bdbd31f0200.png)

My server time is in EDT 
`#date
Thu May  5 17:37:34 EDT 2022`

Wordpress is too.
![image](https://user-images.githubusercontent.com/22225233/167030123-92667c08-d77c-4a0a-a489-4b983cd340ea.png)

And Google Calendar
![image](https://user-images.githubusercontent.com/22225233/167030279-d90c8382-85bb-4cf6-9448-2ba7090de4be.png)

**Comment by malitoor** [comment]
> Same issues here.
> 
> * Calendar works as expected with Apple Calendar and Outlook[,](https://golfwatchcenter.com/) but does not work with Google Calendar at all
> * All calendar entries have the same date in the backend (correct dates are shown in the frontend)

Aww, Thanks:

**Comment by savvasha** [comment]
The wrong date issue was fixed with https://github.com/ThemeBoy/SportsPress/commit/f3fab902f404d48de992378be28ad1163cf02b96
