### ISSUE TITLE
Player list widget: php errors visible on page

### ISSUE THREAD

**Issue by kdw2060** [ThemeBoy/SportsPress#436]
Hi, I use the player widget to only display names and nationality on our website. Other fields like position, number, stats, ... are not shown and not activated/selected in the player list settings.

Since a recent update it seems as if `class-sp-widget-player-list.php` expects these other fields to be there. You can see the generated error/warnings here: https://www.ostaberchem.be/heren-2/

**Comment by savvasha** [comment]
Hi there @kdw2060 ,

The truth is that I am not able to reproduce this issue. Can you try to use a default theme like `Rookie` and disable all your plugins except `SportsPress` to see if there are any conflicts?

Thanks,
Savvas

**Comment by kdw2060** [comment]
Had already tried other teams and disabling some plugins, but that didn't help.
Have switched to a plain shortcode widget in stead of the player list widget now, that solves the issue for me.
