### ISSUE TITLE
Change text to uppercase and modify text

### ISSUE THREAD

**Issue by Sauxinho** [ThemeBoy/SportsPress#437]
How can I change the text that appears automatically?

For example I want to change # to the word DORSAL, and I want to convert the nationality to capital letters, to say ARGENTINA and the date to say APRIL 21, 2020.

Link https://legionclubespro.com/player/murdocc/

Thank you for your help

**Comment by kadimi** [comment]
Please use [the WordPress/SportsPress forums](https://wordpress.org/support/plugin/sportspress/) for support.
