### ISSUE TITLE
Does not uninstall 

### ISSUE THREAD

**Issue by Aaronsss** [ThemeBoy/SportsPress#440]
I tried using sportpress but it doesn't fit my needs so I tried uninstalling it. Uninstalling it fails with the folllowing error

Deletion failed: Error thrownUndefined constant "SP_PLUGIN_FILE"

Wordpress version 6.1.1
Sportpress version  2.7.16

**Comment by savvasha** [comment]
Hi @Aaronsss ,

Did that error occured while you where trying to disable the plugin? What other plugins you have?

Thanks,
Savvas

**Comment by Aaronsss** [comment]
No it disabled fine it's when you come to remove it that it throws the error. 

I had a bit of a play, basically I had to comment out the line that removes the user roles from the uninstall script and then delete them manually afterwards

**Comment by savvasha** [comment]
Can you share the file and the lines you commented out?

**Comment by Aaronsss** [comment]
I think it was these two lines I commented out

https://github.com/ThemeBoy/SportsPress/blob/16b0a3e3a1762598663f38b51b50b662a4e14662/uninstall.php#L21-L22

**Comment by savvasha** [comment]
You are right!
The following commit should fix it!
https://github.com/ThemeBoy/SportsPress/commit/eb444db5b88ef343c72856fd3157a24cd25184fc

Thanks for the heads up!
