### ISSUE TITLE
buddypress integration

### ISSUE THREAD

**Issue by eNnvi** [ThemeBoy/SportsPress#60]
i'd like to have the possiblity to integrate your plugin with buddypress.
For example if you link a wordpress user user to a player the information of that player should be inserted in the profile of the user as additional informations.

The other thing is to allow a user to create a team, invite other members to the team and ask to join a league...

Theese would be veeery good things to add also as a "plugin bridge" between sportspress and buddypress (bp's got very good apis)

**Comment by kishoresahoo** [comment]
I am doing a add-on for sportspress and Buddypress. Need more feedback on this. Till now I have displayed player's single page info in buddypress profile page. Please let me know more ideas. Thanks

**Comment by miroslawlis** [comment]
Buddypress registration page should have option for user to choose team.
Profile page:
editing/adding information: player photo, height, weight, number, position, article and maybe change teams
My two cents
cheers

**Comment by kishoresahoo** [comment]
Here it is : https://shop.opentuteplus.com/product/buddypress-for-sportspress/
