### ISSUE TITLE
CSV Import Events

### ISSUE THREAD

**Issue by ghost** [ThemeBoy/SportsPress#9]
We need a CSV import tool for events. The tool should import basic event info, results, outcomes, and player statistics.

**Comment by supersuryaansh** [comment]
Hey, I am trying to use the tool. I have a number of users On my Wordpress list but using the tool I can only load their usernames in the sportspress and not attach them with a user itself which then has to be done manually using GUI by going at the bottom of the player edit page and assigning a user.

Is there a way I can import users such that they are automatically assigned to the users in my Wordpress website.
